### PR TITLE
cmake: add uninstall build target to aid development cycles

### PR DESCRIPTION
**Pull request by iam-TJ**
Use as: cmake --build your-build-path --target uninstall

Closes issue #530.

### CODE REVIEW

**Comment by hipersayanX** [comment]
I was checking it but [this](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake) looks a much better solution, because the uninstall can work in any platform, while the SackOverflow code only works on Unix like systems. The _cmake_uninstall.cmake.in_ could be put inside [here](https://github.com/webcamoid/webcamoid/tree/master/libAvKys/cmake).

**Comment by iam-TJ** [comment]
That does look much better - I'll test it out. One note - `cmake_uninstall.cmake.in` is supposed to go in the top-level project directory (alongside the top-level `CMakeLists.txt`.

First pass seems reasonably ok. Called it using `cmake --build ../builds/webcamoid  --target uninstall` but a couple of directories are left behind so I'll investigate:
```
$ find /usr/local -wholename '*avkys*' -ls
   524948      4 drwxr-xr-x   2 tj       tj           4096 Jun  3 18:35 /usr/local/lib/avkys
$ find /usr/local -wholename '*webcamoid*' -ls
   540991      4 drwxr-xr-x   2 tj       tj           4096 Jun  3 18:35 /usr/local/share/licenses/webcamoid
```
I'll force-push my current updated branch for now and pause this PR until I've ensured the remaining directories are removed when empty.

**Comment by iam-TJ** [comment]
Took a couple of hours to navigate the intricacies of `cmake` but eventually got there. There isn't a generic fits-all-projects-automatically solution. What I had to do is:
1. alter the suggested `cmake_uninstall.cmake.in` to use (cmake) command `rm -rf` (`remove` and `remove_directory` are deprecated) to allow deleting directories
2. manually append the two project-specific directory paths (`lib/avkys` and `share/licenses/webcamoid`) to the `CMAKE_INSTALL_MANIFEST_FILES` variable during the `install` target so they are written into `install_manifest.txt`.

That allows `cmake_uninstall.cmake` to read the directory names and delete them.

**Comment by hipersayanX** [comment]
Hmm... it will need more work. I installed it in place (as a normal user)

```
cd build-webcamoid-Desktop-Debug
make install DESTDIR="${PWD}/test"
```

And then tried uninstalling with

```
cmake --build "${PWD}" --target uninstall
```

and

```
make uninstall
```

And it just fails.

```
-- Uninstalling /home/user/webcamoid-data/lib/libavkys.so.9.0.0
CMake Error at cmake_uninstall.cmake:16 (message):
  Problem when removing /home/user/webcamoid-data/lib/libavkys.so.9.0.0


make[3]: *** [CMakeFiles/uninstall.dir/build.make:57: CMakeFiles/uninstall] Error 1
make[2]: *** [CMakeFiles/Makefile2:2750: CMakeFiles/uninstall.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2757: CMakeFiles/uninstall.dir/rule] Error 2
make: *** [Makefile:164: uninstall] Error 2
```

The uninstall command is ignoring DESTDIR.

**Comment by iam-TJ** [comment]
> ```
> cd build-webcamoid-Desktop-Debug
> make install DESTDIR="${PWD}/test"
Makes sense it'd fail if `DESTDIR` is being set manually on the command-line since it won't be recorded anywhere by `cmake` or `make`.

Best case is it'd need to be included in the `make DESTDIR="${?PWD}/test uninstall" command. That'd need the cmake uninstall script to include `DESTDIR` since if not set it'd be empty.

However, according to cmake documentation, [using `DESTDIR` will fail on Microsoft Windows](https://cmake.org/cmake/help/latest/envvar/DESTDIR.html).

> Note
> 
> `DESTDIR` may not be used on Windows because installation prefix usually contains a drive letter like in `C:/Program Files` which cannot be prepended with some other prefix.

**Comment by iam-TJ** [comment]
With commit `cmake: uninstall any DESTDIR` it seems to work as required:
```
$ make DESTDIR=/usr/local/webcamoid uninstall
...
-- Uninstalling /usr/local/webcamoid/usr/local/share/metainfo/io.github.webcamoid.Webcamoid.metainfo.xml
-- Uninstalling /usr/local/webcamoid/usr/local/lib/avkys
-- Uninstalling /usr/local/webcamoid/usr/local/share/licenses/webcamoid
running /usr/bin/cmake -E rm -r "/usr/local/webcamoid"  2>&1
Built target uninstall   
```

**Comment by hipersayanX** [comment]
It still failing for me.

```
user@user-VirtualBox:~/build-webcamoid-Desktop-Debug$ make DESTDIR="${PWD}/test" uninstall
-- Uninstalling /home/user/build-webcamoid-Desktop-Debug/test/home/user/webcamoid-data/lib/libavkys.so.9.0.0
CMake Error at cmake_uninstall.cmake:16 (message):
  Problem when removing
  /home/user/build-webcamoid-Desktop-Debug/test/home/user/webcamoid-data/lib/libavkys.so.9.0.0


make[3]: *** [CMakeFiles/uninstall.dir/build.make:57: CMakeFiles/uninstall] Error 1
make[2]: *** [CMakeFiles/Makefile2:2750: CMakeFiles/uninstall.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2757: CMakeFiles/uninstall.dir/rule] Error 2
make: *** [Makefile:164: uninstall] Error 2
```

Even though the file is there and make is aware of it.

```
user@user-VirtualBox:~/build-webcamoid-Desktop-Debug$ ls /home/user/build-webcamoid-Desktop-Debug/test/home/user/webcamoid-data/lib/libavkys.so.9.0.0
/home/user/build-webcamoid-Desktop-Debug/test/home/user/webcamoid-data/lib/libavkys.so.9.0.0
```

I think because you are calling ```cmake -E rm -r``` instead of just calling ```rm -r```. When calling ```cmake -E rm -r``` this is what being executed:

```
cmake -E rm -r /home/user/build-webcamoid-Desktop-Debug/test/home/user/webcamoid-data/lib/libavkys.so.9.0.0
CMake Error: cmake version 3.16.3
Usage: cmake -E <command> [arguments...]
Available commands: 
...
```

That's why it's failing, maybe.

**Comment by iam-TJ** [comment]
The `-E` is to run internal commands and is required. E.g. `man cmake` shows:
```
...
RUN A COMMAND-LINE TOOL
       CMake provides builtin command-line tools through the signature

          cmake -E <command> [<options>]

       Run cmake -E or cmake -E help for a summary of commands.  Available commands are:
...
       rm [-rRf] <file> <dir>...
              Remove the files <file> or directories dir.  Use -r or -R to remove directories and their contents recursively.  If any of the listed files/directories do not exist, the command returns a non-zero exit code,  but  no
              message is logged. The -f option changes the behavior to return a zero exit code (i.e. success) in such situations instead.
```
Is it possible the application is running and has the library open and locked so it cannot be unlinked? I've had quite a few issues when testing that the application doesn't terminate but I don't notice until I try to execute it again, and get a warning about it, but that triggers it to terminate and second attempt to execute is fine!

**Comment by hipersayanX** [comment]
>Is it possible the application is running and has the library open and locked so it cannot be unlinked?

It's a consistent failure, it fails with cmake but the bare command works fine. I've tested it with Ubuntu Focal. The nearest command is

```
       remove [-f] <file>...
              Remove  the  file(s).  If  any  of the listed files already do not exist, the command returns a non-zero exit
              code, but no message is logged. The -f option changes the behavior to return a zero exit code (i.e.  success)
              in  such  situations  instead.   remove  does not follow symlinks. That means it remove only symlinks and not
              files it point to.
```

maybe a solution would be replacing ```rm``` with ```remove```, or checking cmake version and then using one or the other.

**Pull request merged**
