### PR TITLE
- Advanced 'Face-Area' settings for background blur/replacement

### PR DESCRIPTION
**Pull request by cont1nuity**
# Pull request

## Type of change

New feature

## Summary

Adding several new feature options to adjust the recognized face area as enhancement to #250 / #425:
- Scale/Width/Height adjustment
- H-/V-Offset
- Rounded overlay
- Overlay Scale/Width/Height adjustment
- Overlay H-/V-Radius adjustment

These settings allow a clearer cut-out on the face.

### Examples:

Slight height adjustment:
preview1

Width/Height adjustment:
preview2

Scaling:
preview3

"Cutting":
preview4

Round overlay ("face cutout"):
preview5

Overlay adjustment 1:
preview6

Overlay adjustment 2 ("the goal"):
preview7

## Related Issue

This enhances #250 and #425

## More info

N/A

## Added dependencies

N/A

## Target Environment

N/A

### CODE REVIEW

**Comment by hipersayanX** [comment]
Quite pretty good commit, thanks a lot! :smile:

**Comment by cont1nuity** [comment]
Thanks for the merge.
I hope it helps people to keep their privacy in check. 🙂

**Comment by Svetlana-T** [comment]
In what version of webcamoid is this included, please?

**Comment by hipersayanX** [comment]
@Svetlana-T Webcamoid 9.0.0, latest release.

**Comment by Svetlana-T** [comment]
Oh, I'm with 8.5.0 on debian, and they have [8.8.0 as the latest](https://packages.debian.org/search?keywords=webcamoid). is there a .deb generated for the latest release somewhere, please?

**Comment by hipersayanX** [comment]
@Svetlana-T [the AppImage, the installer and the portable](https://github.com/webcamoid/webcamoid/releases/tag/9.0.0).

**Pull request merged**
